pipeline {
    agent any
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
    environment {
        AWS_CREDENTIAL_NAME = "awsEcrCredentials"
        AWS_ACCOUNT_ID = "257307634175"
        REGION = "ap-northeast-2"
        DOCKER_IMAGE_NAME="aws13-spring-petclinic"
        DOCKER_TAG="1.0"
        ECR_REPOSITORY = "${AWS_ACCONT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com"
        ECR_DOCKER_IMAGE = "${ECR_REPOSITORY}/${DOCKER_IMAGE_NAME}"
        ECR_DOCKER_TAG = "${DOCKER_TAG}"
    }
    
  stages {
    stage('Git fatch') {
      steps {
        echo 'git fatch'
         git url: 'https://github.com/jamiesuh/spring-petclinic.git/',
             branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('Maven Build') {
      steps {
        echo 'maven build'
        sh 'mvn -Dmaven.test.failure.ignore=true clean package'
      }
    }  
    stage('Docker Image') {
      steps {
        echo 'docker image'
          dir("${env.WORKSPACE}") {
              sh 'docker build -t aws13-spring-petclinic:1.0 .'
        }
      }
    }  
    stage('Image Push') {
      steps {
        echo 'image push'
      }
    }
    stage('Codedeploy') {
      steps {
        echo 'codedeploy'
      }
    }
  }
}
