pipeline {
    agent any
    tools {
        maven 'M3'
        jdk 'JDK11'
    }
  
  stages {
    stage('Git fatch') {
      steps {
        echo 'git fatch'
         git url: 'https://github.com/jamiesuh/spring-petclinic.git/',
             branch: 'main', credentialsId: 'gitCredential'
      }
    }
    stage('Maven Build') {
      steps {
        echo 'maven build'
        sh 'mnv -Dmaven.test.failure.ignore=true clean package'
      }
    }  
    stage('Docker Image') {
      steps {
        echo 'docker image'
      }
    }  
    stage('Image Push') {
      steps {
        echo 'image push'
      }
    }
    stage('Codedeploy') {
      steps {
        echo 'codedeploy'
      }
    }
  }
}
